apiVersion: v1
kind: ServiceAccount
metadata:
  name: manta-agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manta-agent-role
rules:
- apiGroups:
  - "manta.io"
  resources:
  - replications
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - "manta.io"
  resources:
  - replications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - "manta.io"
  resources:
  - nodetrackers
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manta-agent-binding
subjects:
- kind: ServiceAccount
  name: manta-agent
  namespace: manta-system
roleRef:
  kind: ClusterRole
  name: manta-agent-role
  apiGroup: rbac.authorization.k8s.io
