---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - manta.io
  resources:
  - nodetrackers
  - replications
  - torrents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - manta.io
  resources:
  - nodetrackers/finalizers
  - replications/finalizers
  - torrents/finalizers
  verbs:
  - update
- apiGroups:
  - manta.io
  resources:
  - nodetrackers/status
  - replications/status
  - torrents/status
  verbs:
  - get
  - patch
  - update
